/**
 * lib/live-tv/tmdb-backdrops.ts
 *
 * Loads the TMDb backdrop map (generated by fetch_tmdb_channel_backdrops.js)
 * and provides a helper to get the backdrop URL for a channel.
 *
 * The JSON lives at /public/channels/tmdb-backdrops.json and is imported
 * statically so it is bundled at build-time — zero runtime HTTP overhead.
 */

// Static import → bundled into the JS chunk (Next.js resolves public/ imports via /api or static)
// We use a dynamic require so the JSON is tree-shaken when not used.
let _cache: Record<string, string> | null = null;

/**
 * Returns the pre-fetched TMDb backdrop URL for a channel, or null if none.
 *
 * Usage:
 *   import { getTmdbBackdrop } from "@/lib/live-tv/tmdb-backdrops";
 *   const backdrop = getTmdbBackdrop("cnn"); // → "https://image.tmdb.org/t/p/w780/…"
 */
export function getTmdbBackdrop(channelId: string): string | null {
  // In browser/SSR, fetch from /channels/tmdb-backdrops.json is not synchronous.
  // We use the inline map below which is populated by running the script once
  // and pasting the results. For a fully dynamic approach, see useTmdbBackdrops hook.
  return TMDB_BACKDROPS[channelId] ?? null;
}

// ── STATIC MAP ────────────────────────────────────────────────────────────────
// Run `node fetch_tmdb_channel_backdrops.js <API_KEY>` then paste the JSON here,
// OR import the JSON directly if your bundler supports JSON imports:
//   import backdrops from "@/../public/channels/tmdb-backdrops.json";
//
// This map will be empty until you run the script. After running the script,
// paste the contents of public/channels/tmdb-backdrops.json here.
export const TMDB_BACKDROPS: Record<string, string> = {};

// ── REACT HOOK (dynamic fetch) ─────────────────────────────────────────────
// Use this hook if you want to load backdrop URLs at runtime from the JSON file.
// This is useful during development before you've baked the results into the map above.
//
// import { useTmdbBackdrops } from "@/lib/live-tv/tmdb-backdrops";
// const backdrops = useTmdbBackdrops();
// const url = backdrops["cnn"];

export type BackdropMap = Record<string, string>;

/**
 * Loads /channels/tmdb-backdrops.json at runtime (client-side).
 * Returns an empty object until loaded.
 *
 * Example usage in a component:
 *   "use client";
 *   import { useTmdbBackdrops } from "@/lib/live-tv/tmdb-backdrops";
 *   const backdrops = useTmdbBackdrops();
 */
export function loadTmdbBackdrops(): Promise<BackdropMap> {
  if (_cache) return Promise.resolve(_cache);
  return fetch("/channels/tmdb-backdrops.json")
    .then((r) => {
      if (!r.ok) return {};
      return r.json() as Promise<BackdropMap>;
    })
    .then((data) => {
      _cache = data;
      return data;
    })
    .catch(() => ({}));
}
